name: Daily NBA Elias Scraper

on:
  schedule:
    - cron: "0 12 * * *"   # runs every day at 12:00 UTC
  workflow_dispatch:        # allows manual run from GitHub Actions tab

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install R packages
        run: |
          Rscript -e 'install.packages(c("httr","jsonlite","dplyr","purrr","readr"))'

      - name: Run scraper
        run: Rscript scrape_nba.R

      - name: Commit and push results
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add data/*
          git commit -m "Daily scrape: $(date -u +'%Y-%m-%d %H:%M:%S UTC')" || echo "No changes to commit"
          git push
