name: NBA Scraper

on:
  schedule:
    - cron: "0 12 * * *" # runs daily at 12:00 UTC
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install R dependencies
        run: |
          Rscript -e 'install.packages(c("httr", "jsonlite", "dplyr", "purrr", "readr"))'

      - name: Run scraper
        run: Rscript scrape.R

      - name: Commit and push results
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          mkdir -p data   # ensure folder exists
          git add data || echo "No files to add"
          git commit -m "Daily scrape: $(date -u +'%Y-%m-%d %H:%M:%S UTC')" || echo "No changes to commit"
          git push || echo "No changes to push"
