name: Daily NBA Elias Scraper

on:
  schedule:
    - cron: "0 12 * * *"   # runs every day at 12:00 UTC
  workflow_dispatch:        # manual trigger from GitHub Actions tab

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      # This step installs AND caches R packages
      - name: Install and cache R packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache: true
          packages: |
            any::httr
            any::jsonlite
            any::dplyr
            any::purrr
            any::readr

      - name: Run scraper
        run: Rscript scrape_nba.R

      - name: Commit and push results
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add data/*
          git commit -m "Daily scrape: $(date -u +'%Y-%m-%d %H:%M:%S UTC')" || echo "No changes to commit"
          git push
